### ISSUE TITLE
Investigate scope of #99

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/scraped#100]
Look into what might be going wrong in #99, and whether it's a quick fix. 

If it's quick, fix it now, if not we can work out its relative importance/urgency.

**Comment by chrismytton** [comment]
I've documented the problem into comments on https://github.com/everypolitician/scraped/issues/99. I don't think it's a very quick fix, as it's going to be a bit fiddly and we should probably find a way to inform the user of any errors that occur in the decorator, which means we'll need to fix https://github.com/everypolitician/scraped/issues/9 as a prerequisite.

**Comment by chrismytton** [comment]
Not sure if I should close this now I've done the investigation? I'll think I'll leave it open to remind us to work out the relative importance of fixing this.

**Comment by lucychambers** [comment]
Hi Chris, thanks - if it's not a quick fix - I'll ask @tmtmtmtm to decide if we need to promote it into the sprint. Tony - can you close this when you have made that call?

**Comment by tmtmtmtm** [comment]
I don't think #9 needs to be a pre-requisite for this. That would certainly be a nice additional feature, but at the moment this decorator is unusable on any page where there's a badly encoded URL, which means I think fixing the problem is significantly more important.

I'm not quite sure why this is so fiddly to test for though … @chrismytton?

**Comment by tmtmtmtm** [comment]
I've opened an attempt at this in https://github.com/everypolitician/scraped/pull/101, which seems to gracefully handle this particular problem fine, but I'm not sure if @chrismytton had something else in mind where perhaps this approach might cause problems?

**Comment by chrismytton** [comment]
> I'm not quite sure why this is so fiddly to test for though … @chrismytton?

Ah, I had added almost the same code as you've done in #101, but my code was also printing out a warning, which meant that running the tests produced lots of those warning, hence why I thought #9 would be a prerequisite and testing it would be tricky otherwise!

I will review #101 now 👍

**Comment by chrismytton** [comment]
#101 has now been merged! :tada:
