### ISSUE TITLE
AbsoluteUrls decorator should ensure urls are encoded correctly

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/scraped#52]
# Problem

Currently, the `Scraped::Response::Decorator::AbsoluteUrls` decorator that ships with Scraped doesn't do the `URI.encode`/`URI.decode` dance to ensure URLs are properly encoded.

# Proposed solution

Do the standard `URI.encode`/`URI.decode` dance at [the point where we make relative URLs absolute](https://github.com/everypolitician/scraped/blob/master/lib/scraped/response/decorator/absolute_urls.rb#L18).

# Acceptance criteria

Running https://github.com/everypolitician-scrapers/denmark-folketing/pull/3 should correctly encode the image URLs for that scraper. It's not working at the moment because some URLs have unencoded space characters in them, e.g. `~/media/CV/Foto/2015/S/Yildiz Akdogan/Yildiz_Akdogan_133.jpg.ashx`.

**Comment by chrismytton** [comment]
@ondenman What's the status of this issue? Can it be closed now that #55 has been merged?

**Comment by ondenman** [comment]
@chrismytton Not yet. It isn't yet passing the acceptance test. The Denmark scraper is failing with:
```generic.rb:1102:in `rescue in merge': unrecognised opaque part for mailtoURL: postformand@ft.dk%20/%20dfpksekr@ft.dk (URI::InvalidComponentError)```

**Comment by chrismytton** [comment]
@ondenman Looks like that's a slightly different error from the one this issue was originally tracking. I've opened https://github.com/everypolitician/scraped/issues/65 to track the new error, so I'm closing this one now in favor of that.
