### ISSUE TITLE
Handle JSON documents

### ISSUE THREAD

**Issue by ondenman** [everypolitician/scraped#81]
# Problem
Scraped can handle HTML documents but sometimes data is available as JSON. Scraped does not yet know how to handle JSON.

# Solution
Add a `Scraped::JSON` class to handle JSON documents.

**Comment by chrismytton** [comment]
You can see a prototype of this class in the [myanmar-lower-house-2016](https://github.com/everypolitician-scrapers/myanmar-lower-house-2016/blob/e71eccb4bc45c8ab4dcdaff7d9897aa010d4ef24/lib/scraped/json.rb) and [france-constituencies-mapit](https://github.com/everypolitician-scrapers/france-constituencies-mapit/blob/944d3ce03e88e022c42802ab711cac693ba9b80d/scraper.rb#L15-L33) scrapers.
